# Generated by Django 2.2.2 on 2019-06-09 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0005_book_choice_event_question_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_one',
        ),
        migrations.RemoveField(
            model_name='question',
            name='event',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
